Change default and deprecate requireJREPackageImports, add release note
eclipse/tycho pull request #1151
Opened 2022-07-18 05:33 UTC by laeubi

Fixes https://github.com/eclipse/tycho/issues/1136

2022-07-18 11:47 UTC, laeubi commented
At least none of the integration test care here...

2022-07-18 14:56 UTC, mickaelistria commented
>   You requested to install 'osgi.bundle; org.bouncycastle.bcpg 0.0.0' but it could not be found

This should be fixed now.
If there is some risk of Tycho being broken, I'd rather wait after next I-Build is complete. We didn't have a good build of Platform for 4 days; having 1 proper one before changing Tycho would be useful.

2022-07-19 15:47 UTC, mickaelistria requested changes

2022-07-19 15:47 UTC, mickaelistria commented on tycho-compiler-plugin/src/main/java/org/eclipse/tycho/compiler/AbstractOsgiCompilerMojo.java
> +        if (requireJREPackageImports != null) {
boolean cannot be null, so warning would always show up.

2022-07-19 15:48 UTC, mickaelistria commented
Actually, you don't need to merge this patch to test it on platform. Just submit a PR to the platform parent pom that set the existing flag to `true` and you'll see what happens.

2022-07-19 15:56 UTC, laeubi commented
> Actually, you don't need to merge this patch to test it on platform.

I'll run a aggregator local build, I assume everything is fixed now?

2022-07-19 16:41 UTC, mickaelistria commented
>  assume everything is fixed now?

Yes.

> I'll run a aggregator local build,

As you prefer, but sending a PR will trigger a full build without running tests on CI.

2022-07-19 17:15 UTC, merged