Apply changes auto done by pde to target files.
eclipse/tycho pull request #532
Opened 2022-01-11 14:45 UTC by akurtakov

2022-01-11 18:51 UTC, akurtakov commented
@laeubi as pde changes these I thought it's good idea to push the changes but tests are failing. What should we do here?

2022-01-11 18:57 UTC, laeubi commented
I would not change existing integration tests as these also test legacy behavior for backward compatibilty to old format.
Also if you update make sure to use the latest m2e-snapshot as some never features are not present in the current release.

2022-01-11 19:10 UTC, akurtakov commented
> I would not change existing integration tests as these also test legacy behavior for backward compatibilty to old format. Also if you update make sure to use the latest m2e-snapshot as some never features are not present in the current release.

Problem with keeping them is that if one just opens the target platform page these files are changed and one has to manually revert changes in them.

2022-01-11 19:16 UTC, laeubi commented
I know, but it should not be necessary to open them at all I think. Don't know if we can mark them to ignore changes with some git property?

2022-01-11 19:17 UTC, laeubi commented
BTW: the changes in `tycho-bundles-target.target` should be fine and the only one to work with on a regular basis.

2022-01-12 05:23 UTC, laeubi requested changes
I would propose that we only change the tycho-bundles.target file and leave the other ones alone.
These other targets are essentially test-resources and should never be touched/modified.

2022-01-12 05:23 UTC, laeubi commented on tycho-its/projects/target.maven.autofeature/test.target
> -
This change seems to indicate that not the latest m2e-snapshot is used here and what makes the test fail

2022-01-12 05:23 UTC, laeubi commented on tycho-bundles/org.eclipse.tycho.p2.resolver.impl.test/resources/targetresolver/mavenDep.target
> +		<location includeDependencyScope="compile" missingManifest="ignore" type="Maven">
This removes the latest changes from m2e so maybe another reason why the test fails.

2022-01-12 06:00 UTC, akurtakov commented
OK, I'm giving up on this one as I clearly haven't followed deep enough and don't have latest snapshots of everything.

2022-01-12 06:00 UTC, closed without merging