TychoGraphBuilder: -amd should pick up dependencies of dependants
eclipse/tycho pull request #608
Opened 2022-02-01 10:42 UTC by sratz

`-amd` in general is of little practical use in Tycho build environments that typically contain downstream features + updatesites that depend on practically everything.

To make it somewhat useful (i.e. get something buildable in the first place out of it), `-amd` should pick up dependencies of dependents.

Also add a few more integration tests.

Change-Id: I0538fb5bd285c8d2d4132e95c4d44d09c5b2026c

2022-02-01 10:48 UTC, laeubi requested changes

2022-02-01 10:48 UTC, laeubi commented on tycho-build/src/main/java/org/eclipse/tycho/build/TychoGraphBuilder.java
>  								// make behaviors are both false here as projectDependenciesMap includes transitive already
The comment here seems outdated

2022-02-01 10:51 UTC, sratz commented on tycho-build/src/main/java/org/eclipse/tycho/build/TychoGraphBuilder.java
>  								// make behaviors are both false here as projectDependenciesMap includes transitive already
Done

2022-02-01 10:53 UTC, laeubi approved these changes

2022-02-01 10:59 UTC, joeshannon commented
I'm not sure about this as I think it will imply a behaviour difference between vanilla maven vs tycho which may be unexpected by users.

In general for non-linear dependency relations, both -am and -amd would typically have to be used as far as I understand it.

I will just upload a demo vanilla maven project to demonstrate.

2022-02-01 11:12 UTC, laeubi commented
@joeshannon I don't know as its a bit unclear how it is supposed to work.
From a user perspective I would find it rather strange if I have to add all the transitive projects manually, but maybe that how it is supposed to work?

2022-02-01 11:49 UTC, joeshannon commented
Yes I have to admit I am also not hugely experienced with using these options in practice outside of simple builds so I am happy to concede to other views as to how this should behave. I was approaching this by attempting to match the behaviour of a pure maven demo. [Here is that demo](https://github.com/joeshannon/simple-maven-reactor). I'll look at adding the additional modules as presented in this PR in a bit.

Whether we want to modify this behaviour in Tycho to enhance common use cases is another question I guess.

2022-02-01 12:04 UTC, laeubi commented
If we want to say that[ this document is normative](https://blog.sonatype.com/2009/10/maven-tips-and-tricks-advanced-reactor-options/) they state:

> If you wanted to run a portion of the larger build, you would use the -pl or --projects option with the -am or --also-make option. When you specify a project with the -am option, Maven will build all of the projects that the specified project depends upon (either directly or indirectly). Maven will examine the list of projects and walk down the dependency tree, finding all of the projects that it needs to build.

So if `-pl A` and specify `-am` would require that i build A and everything A depends on transitively this should work without adding anything beside the computed dependencies, as Tycho already computes a set of all transitive requirements. As mentioned above, for this we should even be able to skip computation of *all* projects dependencies but shortcircuit to only compute them for `A` (even we need to examine all others for their metadata).

> the -amd or --also-make-dependents option configures Maven to build a project and any project that depends on that project. When using --also-make-dependents, Maven will examine all of the projects in our reactor to find projects that depend on a particular project. It will automatically build those projects and nothing else.

Given that `-pl A` and specify `-amd` should only add _direct_ dependencies but not transitive ones! Even though I have no idea for what this is useful as it only will work for 'flat' structures, this will require to compute *all* project dependencies to be computed to find out who needs `A` but don't add anything else.

The interesting part would be (and that's what is not mentioned here) if we specify *both* options, should we only add dependencies of specified  projects and what depends on them but not the dependent dependencies ...?

2022-02-02 12:48 UTC, laeubi commented
@sratz it seems one test is still failing do you plan to take a look at this?

2022-02-02 16:56 UTC, laeubi approved these changes

2022-02-02 16:56 UTC, merged

2022-02-02 16:56 UTC, laeubi commented
Thanks for the testcase + fix